---
title: "Exploratory Data Analysis for `std-year.csv`"
author: "Enqun Wang (EW)"
date: "May 29, 2016"
output:
  pdf_document: default
  html_notebook: default
---


### Setup

```{r}
setwd("/Users/ewenwang/Documents/Meteorology/1-data/datasets")

# load packages
require(ggmap)
require(ggplot2)
require(RColorBrewer)

# load data
df = read.csv("std-year.csv", skip = 1, header = F)
```

### Cumulative Annual Sunshine Hours


**EW:** The data are from column 2, 3, and 93 in `std-year.csv`, conresponding to `latitude`, `longtitude`, and `cumulative annual sunshine hours`.

We try to make a contour plot.

```{r}
# preprocess data
sunlight = df[,c(2, 3, 93)]

colnames(sunlight) = c("lat", "lon", "hours")

sunlight$lat = sunlight$lat/100
sunlight$lon = sunlight$lon/100


## Specify a map with center at the center of all the coordinates
mean.longitude <- mean(sunlight$lon)
mean.latitude <- mean(sunlight$lat)

center = c(lon = mean.longitude, lat = mean.latitude)
map = get_map(location = center, zoom = 4, color = "bw")

ggmap(map, extent = "panel", maprange=FALSE) +
  geom_density2d(data = sunlight, aes(x = lon, y = lat)) +
  stat_density2d(data = sunlight, aes(x = lon, y = lat,  
                               fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 16, geom = 'polygon') +
  scale_fill_gradient(low = "green", high = "red") +
  scale_alpha(range = c(0.00, 0.25), guide = FALSE) +
  theme(legend.position = "none", axis.title = element_blank(), 
        text = element_text(size = 12))
```

